from .function_table_one import create_table_one #type: ignore
from .function_tourmis_table import create_tourmis_table #type: ignore
from .function_table_two import create_table_two #type: ignore
from .function_benchmarking_alliance_table import create_benchmarking_alliance_table #type: ignore
from .function_tøbbe_table import create_tøbbe_table #type: ignore
from .function_create_hotel_capacity_table import create_hotel_capacity_table #type: ignore
from .function_create_hotel_capacity_graph import create_hotel_capacity_graph #type: ignore
from .function_create_styled_occupancy_table import create_styled_occupancy_table #type: ignore
from .function_create_styled_capacity_table import create_styled_capacity_table #type: ignore